### ISSUE TITLE
Crash during ad loading

### ISSUE THREAD

**Issue by dmitryfisko** [ChartBoost/android-sdk-sample-java#34]
SDK version: 9.3.1
Crash occurs after app storage clean up
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
... 1 more
Caused by: java.lang.Exception: Request failed due to status code 403 in message
at com.chartboost.sdk.impl.q6.a(SourceFile:151)
at com.chartboost.sdk.impl.z3.a(SourceFile:22)
at com.chartboost.sdk.impl.r1.a(SourceFile:93)
at com.chartboost.sdk.impl.l4.run(SourceFile:6)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7872)
... 3 more
```

**Comment by dmitryfisko** [comment]
Looks like crash going at least from 9.0.0
Problem occurs due to 403 response, may be it's possible to fix on backend

**Comment by stosiarz** [comment]
@dmitryfisko Could you please point out which network call fails with 403? Provided stack trace doesn't lead me to code that can fail. Also you mentioned "Crash occurs after app storage clean up". Could you provide steps of reproduction like clean the storage and then init the sdk or clean storage and cache the sdk? Thank you for your help.
